const express = require('express');
const serveStatic = require('serve-static');
const path = require('path');

const app = express();

// Serve the static files generated by the Vue.js build process
app.use(serveStatic(path.join(__dirname, 'dist')));

// Handle all other routes by serving the index.html file
app.get('*', (req, res) => {
    console.log('Serving index.html');
  res.sendFile(path.join(__dirname, 'dist/index.html'));
});

// Set the server to listen on a specified port, defaulting to 3000 if the PORT environment variable is not set
const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Server is running on port ${port}`);
});
